### PR TITLE
Add Django 1.11 support

### PR DESCRIPTION
**Pull request by jwhitlock**
Test Django 1.11, including test options in [Django 1.10](https://docs.djangoproject.com/en/1.11/releases/1.10/#tests) and [1.11](https://docs.djangoproject.com/en/1.11/releases/1.11/#tests)

### CODE REVIEW

**Comment by alkaros2506** [comment]
May I ask if there's going to be a release with this fix included in the near future?

**Comment by jwhitlock** [comment]
I haven't released a new version because the changes were all to the test app. The current release should work in Django 1.11 as well.

**Comment by jwhitlock** [comment]
However, if one person takes the time to comment, there's probably another 10 who had the same issue and didn't. I'll release a new django-nose in the next 5 days.

**Comment by alkaros2506** [comment]
Much appreciated. Thank you very much

**Comment by jwhitlock** [comment]
Released: https://pypi.python.org/pypi/django-nose/1.4.5

**Pull request merged**
