### PR TITLE
use new app loading system when possbile, fixes django-nose for current master

### PR DESCRIPTION
**Pull request by dgladkov**
Fixes for stuff that was removed in current Django master according to deprecation cycle

### CODE REVIEW

**Comment by dgladkov** [comment]
Any news on merging this PR?

Django source with the same compatibility shims for reference:
https://github.com/django/django/blob/1.8.2/django/db/models/loading.py#L16
https://github.com/django/django/blob/1.8.2/django/apps/registry.py#L391

**Comment by jwhitlock** [comment]
Does this target Django 1.8 or Django 1.9?

**Comment by dgladkov** [comment]
It targets current master branch (pre-1.9)

**Comment by jwhitlock** [comment]
I'm inclined to wait until the first beta to tackle 1.9 issues.  However, if you can get .travis.cfg working with Django master (with an [allowed failure](http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail) config), and show passing tests, I'll merge.

**Comment by dgladkov** [comment]
@jwhitlock Done, also added tox config and configured Travis to run tox builds. Added Python 3.5 test run against django-master according to https://docs.djangoproject.com/en/1.8/faq/install/#what-python-version-can-i-use-with-django, although it seems that Travis does not support Python 3.5 builds yet

**Comment by jwhitlock** [comment]
Thanks for you work on this, @dgladkov.

**Pull request merged**
